// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCgGNzKTn4Z3ECiHPLrweClD5CafZZgeo',
    appId: '1:666463032787:web:5ca9cf70c7d8f726d88b26',
    messagingSenderId: '666463032787',
    projectId: 'testing-cli-188c7',
    authDomain: 'testing-cli-188c7.firebaseapp.com',
    storageBucket: 'testing-cli-188c7.appspot.com',
    measurementId: 'G-L6MX41NLY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx4Po98ttiSgujFCblv23ZmTIhQbcAXbg',
    appId: '1:666463032787:android:9369e81adec819d8d88b26',
    messagingSenderId: '666463032787',
    projectId: 'testing-cli-188c7',
    storageBucket: 'testing-cli-188c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOWOlLauELiZEdCnR_-HCOb-WAy6qUSYM',
    appId: '1:666463032787:ios:0ea0d17c7b4e9769d88b26',
    messagingSenderId: '666463032787',
    projectId: 'testing-cli-188c7',
    storageBucket: 'testing-cli-188c7.appspot.com',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOWOlLauELiZEdCnR_-HCOb-WAy6qUSYM',
    appId: '1:666463032787:ios:0ea0d17c7b4e9769d88b26',
    messagingSenderId: '666463032787',
    projectId: 'testing-cli-188c7',
    storageBucket: 'testing-cli-188c7.appspot.com',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCgGNzKTn4Z3ECiHPLrweClD5CafZZgeo',
    appId: '1:666463032787:web:988e68864ebbccc1d88b26',
    messagingSenderId: '666463032787',
    projectId: 'testing-cli-188c7',
    authDomain: 'testing-cli-188c7.firebaseapp.com',
    storageBucket: 'testing-cli-188c7.appspot.com',
    measurementId: 'G-QF7WSYLVHB',
  );
}
